### ISSUE TITLE
Setting text color for lsm_dom_view_render

### ISSUE THREAD

**Issue by diamondburned** [mjakeman/lasem#17]
Is there a way to change the default text color that `lsm_dom_view_render` outputs?

Calling `cairo_set_source_rgba` doesn't seem to work; the color is probably overridden in the code somewhere.

**Comment by mjakeman** [comment]
Yes, that's possible.

Lasem uses a cascade for styling (like CSS). You can get/set a default style on the root element ( `LsmMathmlMathElement`) and change the default colour using that. For specific elements, Lasem also respects the `mathcolor` attribute in your MathML.

Something like this:
```c
LsmMathmlMathElement *root = lsm_mathml_document_get_root_element (LSM_MATHML_DOCUMENT (my_mathml_document));
LsmMathmlStyle *style = lsm_mathml_math_element_get_default_style (root);
lsm_mathml_style_set_math_color (style, 51 / 255.0f, 209 / 255.0f, 122 / 255.0f, 1.0f);
lsm_mathml_math_element_set_default_style (root, style);
```

Which will render the equation like so (the pink '4' comes from the MathML attribute taking precedence over the default style):

![image](https://user-images.githubusercontent.com/12368711/156273134-16b101d6-ad01-4a9a-8123-f707c8acb23d.png)

**Comment by mjakeman** [comment]
Re: Using Lasem, just a quick note.

I forked the project a few months ago and 'revived' it by rewriting the build system with meson, with the goal of using it in modern GTK applications. My current plans are to drop SVG rendering support (since librsvg already exists and is much more complete) and focus exclusively on MathML rendering.

If you don't mind, what are you thinking of using Lasem for? My use-case is supporting inline equations inside my [word processor](https://github.com/mjakeman/bluetype). I'd like to understand what others are using it for, to hopefully attract more contributors down the line :)

**Comment by diamondburned** [comment]
> If you don't mind, what are you thinking of using Lasem for? My use-case is supporting inline equations inside my [word processor](https://github.com/mjakeman/bluetype). I'd like to understand what others are using it for, to hopefully attract more contributors down the line :)

I'm using it to make a semi-WYSIWYG Markdown editor that I can use to take notes with.

**Comment by diamondburned** [comment]
> Something like this:
> 
> ```c
> LsmMathmlMathElement *root = lsm_mathml_document_get_root_element (LSM_MATHML_DOCUMENT (my_mathml_document));
> LsmMathmlStyle *style = lsm_mathml_math_element_get_default_style (root);
> lsm_mathml_style_set_math_color (style, 51 / 255.0f, 209 / 255.0f, 122 / 255.0f, 1.0f);
> lsm_mathml_math_element_set_default_style (root, style);
> ```

It seems like `lsm_mathml_style_set_math_color` isn't introspected into the GIR file, which probably explains why I couldn't see any function to change the color. Is this intentional?

**Comment by diamondburned** [comment]
I think for now, I'll try and modify the MathML string until I can figure out a better way.

**Comment by mjakeman** [comment]
> It seems like lsm_mathml_style_set_math_color isn't introspected into the GIR file, which probably explains why I couldn't see any function to change the color. Is this intentional?

Definitely not intentional - it's a Boxed type so it should work transparently. Likely an issue with the way the header files are set up. Introspection also affects the online docs (as they use gi-docgen) so I've opened a new issue for it.

> I'm using it to make a semi-WYSIWYG Markdown editor that I can use to take notes with.

Nice! I'll keep an eye out for it

**Comment by diamondburned** [comment]
> @diamondburned Introspection should now be fixed on master

It seems like `LsmDomDocument` is completely gone now. Is that intentional?

**Comment by mjakeman** [comment]
Odd. I've pushed a fix, can you check now?

**Comment by diamondburned** [comment]
> Odd. I've pushed a fix, can you check now?

That fixed it. Thank you.
