### ISSUE TITLE
Tagging 0.7

### ISSUE THREAD

**Issue by McSinyx** [mjakeman/lasem#22]
The latest tagged release was 0.4.4/0.5.1, which was over three years ago.  BTW could you please pull the [tag information](https://gitlab.gnome.org/Archive/lasem/-/tags) here?

**Comment by mjakeman** [comment]
Hi sorry for the delay, I've tagged 0.7 and added tag information from the original repository.

See: [Release Lasem 0.7](https://github.com/mjakeman/lasem/releases/tag/LASEM_0_7_0)

Regarding the state of the library, I do not have any short-term plans to work on Lasem and there is no API stability guaranteed, though I will continue to review PRs, tag releases, and do general maintenance in keeping it up to date with GTK and the rest of the GNOME stack.

Long term, I plan to use this library in my own projects, so it is definitely not abandoned. I'd like to add a GPU-accelerated backend for GTK 4 and some machinery for equation editing eventually.

**Comment by McSinyx** [comment]
Awesome, thanks!
