### ISSUE TITLE
Relationship to LasemProject

### ISSUE THREAD

**Issue by jtojnar** [mjakeman/lasem#23]
The original author moved to GitHub as reported in https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/608. I previously thought it was this repo but apparently it is https://github.com/LasemProject/lasem.

Do you think it would be feasible to merge the two forks together?

**Comment by mjakeman** [comment]
Hi, thanks for pointing this out.

I wasn't at all aware there was any continuation of Lasem, and only forked under the assumption development had stopped.

I've opened an issue on the main lasem repo. I'd be happy to converge around upstream if development is ongoing.

**Comment by mjakeman** [comment]
This fork is now deprecated 🎉 

All changes have been merged into the upstream Lasem project.
